# Generated by Django 6.0 on 2025-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('fastfood', 'Fast Food'), ('national', 'National Foods'), ('drink', 'Drinks'), ('dessert', 'Desserts')], max_length=20),
        ),
    ]
